from __future__ import annotations

RESEARCH_INTENT_ANALYSIS_NODE_ID = "research-intent-analysis"
RESEARCH_PRIVACY_GUARD_NODE_ID = "research-privacy-guard"
RESEARCH_QUERY_PLAN_NODE_ID = "research-query-plan"
RESEARCH_PARALLEL_SEARCH_NODE_ID = "research-parallel-search"
RESEARCH_SOURCE_REVIEW_NODE_ID = "research-source-review"
RESEARCH_SOURCE_READING_NODE_ID = "research-source-reading"
RESEARCH_REPORT_SYNTHESIS_NODE_ID = "research-report-synthesis"
RESEARCH_REPORT_QUALITY_CHECK_NODE_ID = "research-report-quality-check"
RESEARCH_MARKDOWN_OUTPUT_NODE_ID = "research-markdown-output"

RESEARCH_FLOW_NODE_IDS = {
    RESEARCH_INTENT_ANALYSIS_NODE_ID,
    RESEARCH_PRIVACY_GUARD_NODE_ID,
    RESEARCH_QUERY_PLAN_NODE_ID,
    RESEARCH_PARALLEL_SEARCH_NODE_ID,
    RESEARCH_SOURCE_REVIEW_NODE_ID,
    RESEARCH_SOURCE_READING_NODE_ID,
    RESEARCH_REPORT_SYNTHESIS_NODE_ID,
    RESEARCH_REPORT_QUALITY_CHECK_NODE_ID,
    RESEARCH_MARKDOWN_OUTPUT_NODE_ID,
}

RESEARCH_DATA_DEPENDENT_NODE_IDS = {
    RESEARCH_PRIVACY_GUARD_NODE_ID,
    RESEARCH_QUERY_PLAN_NODE_ID,
    RESEARCH_PARALLEL_SEARCH_NODE_ID,
    RESEARCH_SOURCE_REVIEW_NODE_ID,
    RESEARCH_SOURCE_READING_NODE_ID,
    RESEARCH_REPORT_SYNTHESIS_NODE_ID,
    RESEARCH_REPORT_QUALITY_CHECK_NODE_ID,
    RESEARCH_MARKDOWN_OUTPUT_NODE_ID,
}


def research_flow_template() -> dict[str, object]:
    return {
        "kind": "research",
        "nodeIds": sorted(RESEARCH_FLOW_NODE_IDS),
        "dataDependentNodeIds": sorted(RESEARCH_DATA_DEPENDENT_NODE_IDS),
        "entryNodeId": RESEARCH_INTENT_ANALYSIS_NODE_ID,
        "outputNodeId": RESEARCH_MARKDOWN_OUTPUT_NODE_ID,
    }
